#!/bin/bash
#
#Recorre un vector e imprime solo los numeros pares y los numeros inpares los cuenta y al final imprime la cantidad.
#
# con este arreglo denbe imprimir: "pares: 2 4 5 6, impares: 5" 
arreglo=(1 2 3 4 5 6 7 8  9)

impares=0

res=""

for num in ${arreglo[@]}; do
	res="Pares:"
	if [ $(($num % 2)) -eq 0 ]; then
		res="${res} $num"
	else
		$((impares++))
	fi
	res="${res}impares: $impares"
done

echo "$res"
exit 0
	
