#!/bin/bash
#
#Renombra los archivos en un directorio pasado como parametro, agregando al principio o al final
#de su nombre una cadena de texto tambien pasada por parametro.

if [ $# -ne 3 ]; then
	echo "Se deben pasar 3 parametros y se pasaron $#"
	exit 1
fi

if [ "$2" != "-a" ] && [ "$2" != "-b" ]; then
	echo "Parametro erroneo."
fi

if [ -e "$1" ] && [ -d "$1" ]; then
	IFS=$"\n" directorio=($(ls $1))
	unset IFS
	for archivo in $directorio; do
		if [ -f archivo ]; then
			if [ "$2" = "-a" ]; then
				$(mv ""$1"${archivo}" ""$1"${archiv}o"$3"")
			else
				$(mv "${$1}${$archivo}" "${$1}${$3}${$archivo}")
			fi
		fi
	done
else
	echo "Ingrese un directorio valido."
	exit 1
fi

